AppBundle\Entity\Directorio:
    type: entity
    table: Directorio
    indexes:
        fk_Directorio_Directorio1_idx:
            columns:
                - parentId
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        path:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    manyToOne:
        parentid:
            targetEntity: Directorio
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                parentId:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        idespacioalmacenamientohasdirectorio:
            targetEntity: Espacioalmacenamiento
            cascade: {  }
            mappedBy: iddirectorio
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
