AppBundle\Entity\Logs:
    type: entity
    table: logs
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tipo:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        fecha:
            type: date
            nullable: true
            comment: ''
        mensaje:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
