AppBundle\Entity\Usuario:
    type: entity
    table: Usuario
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        password:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        nombre:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        apellidos:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        correo:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
